---

- name: create hbase thrift systemd service file
  template:
    src: systemd/hbase-thrift.service.j2
    dest: /etc/systemd/system/hbase-thrift.service
  notify:
  - reload systemd
  - restart hbase-thrift

- name: start hbase thrift
  service:
    name: hbase-thrift
    state: started
    enabled: yes
